CREATE TABLE Category (
	id SERIAL PRIMARY KEY,
	name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE Joke (
	id SERIAL PRIMARY KEY,
	content VARCHAR(255) NOT NULL,
	likes INTEGER DEFAULT 0 NOT NULL,
	dislikes INTEGER DEFAULT 0 NOT NULL,
	category_id INTEGER NOT NULL,
	CONSTRAINT fk_category FOREIGN KEY (category_id) REFERENCES Category(id) ON DELETE CASCADE
);